### PR TITLE
Add two options owner_url and owner_name for customizing the footer.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by benbalter** [comment]
@xuhdev I believe you can accomplish this via the following in your config:

```yml
github:
  owner_name: foo
  owner_url: bar
```

**Comment by xuhdev** [comment]
@benbalter Thanks! Perhaps we should document them?

**Comment by xuhdev** [comment]
@benbalter I just tried your method, but it does not seem to work...

**Comment by benbalter** [comment]
@xuhdev Is this still a problem?

**Pull request closed without merging**
